name: "Platform Self-Service Pipeline"

on:
  push:
    branches: ["main"]

jobs:
  validate-and-provision:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infrastructure

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init -input=false
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TFC_TOKEN }}

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TFC_TOKEN }}
